# Generated by Django 5.0.1 on 2024-01-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('applied_date', models.DateTimeField(auto_now=True)),
                ('opened', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('url', models.TextField()),
                ('opened_date', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('total_visits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('total_visits', models.IntegerField(default=0)),
                ('locations', models.ManyToManyField(blank=True, to='main_site.location')),
            ],
        ),
    ]
