# Generated by Django 5.0.1 on 2024-01-13 07:14

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytrack',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
