# Generated by Django 5.0.1 on 2024-01-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_alter_companytrack_country_alter_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytrack',
            name='tracker_id',
            field=models.TextField(),
        ),
    ]
