# Generated by Django 5.0.1 on 2024-01-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_alter_companytrack_tracker_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companytrack',
            name='id',
        ),
        migrations.AlterField(
            model_name='companytrack',
            name='tracker_id',
            field=models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
