# Generated by Django 5.0.1 on 2024-01-13 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_remove_companytrack_id_alter_companytrack_tracker_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='companytrack',
            name='tracker_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_key', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('apis', models.ManyToManyField(blank=True, to='main_site.api')),
            ],
        ),
    ]
