# Generated by Django 5.0.1 on 2024-01-13 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_api_alter_companytrack_tracker_id_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='license_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.license'),
        ),
    ]
