# Generated by Django 5.0.1 on 2024-01-14 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_alter_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytrack',
            name='applied_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
