# Generated by Django 5.0.1 on 2024-01-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_alter_companytrack_applied_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytrack',
            name='file_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
