# Generated by Django 5.0.1 on 2024-01-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_companytrack_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companytrack',
            name='file_id',
        ),
        migrations.AddField(
            model_name='companytrack',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='main_site/upload/'),
        ),
    ]
