# Generated by Django 5.0.1 on 2024-01-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0011_remove_companytrack_file_id_companytrack_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
        migrations.AlterField(
            model_name='companytrack',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
